# Generated by Django 4.0.1 on 2022-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.IntegerField(default=0),
        ),
    ]
