# Generated by Django 4.0.1 on 2022-01-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_order_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
